app:
  name: LLM Guard API
  scan_fail_fast: false
  scan_prompt_timeout: 120
  scan_output_timeout: 120
  lazy_load: true

input_scanners:
  - type: PromptInjection
  - type: TokenLimit
    params:
      limit: 4096

output_scanners:
  - type: FactualConsistency
    params:
      minimum_score: 0.5
  - type: Relevance
    params:
      threshold: 0.5
  - type: NoRefusal
    params:
      threshold: 0.5
      match_type: full
